package com.chess.mybatis.entity;

import java.util.Date;

public class NoticeTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_table.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_table.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_table.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_table.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_table.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_table.create_persion
     *
     * @mbggenerated
     */
    private String createPersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_table.id
     *
     * @return the value of notice_table.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_table.id
     *
     * @param id the value for notice_table.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_table.content
     *
     * @return the value of notice_table.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_table.content
     *
     * @param content the value for notice_table.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_table.title
     *
     * @return the value of notice_table.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_table.title
     *
     * @param title the value for notice_table.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_table.type
     *
     * @return the value of notice_table.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_table.type
     *
     * @param type the value for notice_table.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_table.create_time
     *
     * @return the value of notice_table.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_table.create_time
     *
     * @param createTime the value for notice_table.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_table.create_persion
     *
     * @return the value of notice_table.create_persion
     *
     * @mbggenerated
     */
    public String getCreatePersion() {
        return createPersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_table.create_persion
     *
     * @param createPersion the value for notice_table.create_persion
     *
     * @mbggenerated
     */
    public void setCreatePersion(String createPersion) {
        this.createPersion = createPersion == null ? null : createPersion.trim();
    }
}