package com.chess.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RoomInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    public RoomInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGameTypeIsNull() {
            addCriterion("game_type is null");
            return (Criteria) this;
        }

        public Criteria andGameTypeIsNotNull() {
            addCriterion("game_type is not null");
            return (Criteria) this;
        }

        public Criteria andGameTypeEqualTo(String value) {
            addCriterion("game_type =", value, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameTypeNotEqualTo(String value) {
            addCriterion("game_type <>", value, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameTypeGreaterThan(String value) {
            addCriterion("game_type >", value, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameTypeGreaterThanOrEqualTo(String value) {
            addCriterion("game_type >=", value, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameTypeLessThan(String value) {
            addCriterion("game_type <", value, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameTypeLessThanOrEqualTo(String value) {
            addCriterion("game_type <=", value, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameTypeLike(String value) {
            addCriterion("game_type like", value, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameTypeNotLike(String value) {
            addCriterion("game_type not like", value, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameTypeIn(List<String> values) {
            addCriterion("game_type in", values, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameTypeNotIn(List<String> values) {
            addCriterion("game_type not in", values, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameTypeBetween(String value1, String value2) {
            addCriterion("game_type between", value1, value2, "gameType");
            return (Criteria) this;
        }

        public Criteria andGameTypeNotBetween(String value1, String value2) {
            addCriterion("game_type not between", value1, value2, "gameType");
            return (Criteria) this;
        }

        public Criteria andMaIsNull() {
            addCriterion("ma is null");
            return (Criteria) this;
        }

        public Criteria andMaIsNotNull() {
            addCriterion("ma is not null");
            return (Criteria) this;
        }

        public Criteria andMaEqualTo(Integer value) {
            addCriterion("ma =", value, "ma");
            return (Criteria) this;
        }

        public Criteria andMaNotEqualTo(Integer value) {
            addCriterion("ma <>", value, "ma");
            return (Criteria) this;
        }

        public Criteria andMaGreaterThan(Integer value) {
            addCriterion("ma >", value, "ma");
            return (Criteria) this;
        }

        public Criteria andMaGreaterThanOrEqualTo(Integer value) {
            addCriterion("ma >=", value, "ma");
            return (Criteria) this;
        }

        public Criteria andMaLessThan(Integer value) {
            addCriterion("ma <", value, "ma");
            return (Criteria) this;
        }

        public Criteria andMaLessThanOrEqualTo(Integer value) {
            addCriterion("ma <=", value, "ma");
            return (Criteria) this;
        }

        public Criteria andMaIn(List<Integer> values) {
            addCriterion("ma in", values, "ma");
            return (Criteria) this;
        }

        public Criteria andMaNotIn(List<Integer> values) {
            addCriterion("ma not in", values, "ma");
            return (Criteria) this;
        }

        public Criteria andMaBetween(Integer value1, Integer value2) {
            addCriterion("ma between", value1, value2, "ma");
            return (Criteria) this;
        }

        public Criteria andMaNotBetween(Integer value1, Integer value2) {
            addCriterion("ma not between", value1, value2, "ma");
            return (Criteria) this;
        }

        public Criteria andZimoIsNull() {
            addCriterion("zimo is null");
            return (Criteria) this;
        }

        public Criteria andZimoIsNotNull() {
            addCriterion("zimo is not null");
            return (Criteria) this;
        }

        public Criteria andZimoEqualTo(String value) {
            addCriterion("zimo =", value, "zimo");
            return (Criteria) this;
        }

        public Criteria andZimoNotEqualTo(String value) {
            addCriterion("zimo <>", value, "zimo");
            return (Criteria) this;
        }

        public Criteria andZimoGreaterThan(String value) {
            addCriterion("zimo >", value, "zimo");
            return (Criteria) this;
        }

        public Criteria andZimoGreaterThanOrEqualTo(String value) {
            addCriterion("zimo >=", value, "zimo");
            return (Criteria) this;
        }

        public Criteria andZimoLessThan(String value) {
            addCriterion("zimo <", value, "zimo");
            return (Criteria) this;
        }

        public Criteria andZimoLessThanOrEqualTo(String value) {
            addCriterion("zimo <=", value, "zimo");
            return (Criteria) this;
        }

        public Criteria andZimoLike(String value) {
            addCriterion("zimo like", value, "zimo");
            return (Criteria) this;
        }

        public Criteria andZimoNotLike(String value) {
            addCriterion("zimo not like", value, "zimo");
            return (Criteria) this;
        }

        public Criteria andZimoIn(List<String> values) {
            addCriterion("zimo in", values, "zimo");
            return (Criteria) this;
        }

        public Criteria andZimoNotIn(List<String> values) {
            addCriterion("zimo not in", values, "zimo");
            return (Criteria) this;
        }

        public Criteria andZimoBetween(String value1, String value2) {
            addCriterion("zimo between", value1, value2, "zimo");
            return (Criteria) this;
        }

        public Criteria andZimoNotBetween(String value1, String value2) {
            addCriterion("zimo not between", value1, value2, "zimo");
            return (Criteria) this;
        }

        public Criteria andHongIsNull() {
            addCriterion("hong is null");
            return (Criteria) this;
        }

        public Criteria andHongIsNotNull() {
            addCriterion("hong is not null");
            return (Criteria) this;
        }

        public Criteria andHongEqualTo(String value) {
            addCriterion("hong =", value, "hong");
            return (Criteria) this;
        }

        public Criteria andHongNotEqualTo(String value) {
            addCriterion("hong <>", value, "hong");
            return (Criteria) this;
        }

        public Criteria andHongGreaterThan(String value) {
            addCriterion("hong >", value, "hong");
            return (Criteria) this;
        }

        public Criteria andHongGreaterThanOrEqualTo(String value) {
            addCriterion("hong >=", value, "hong");
            return (Criteria) this;
        }

        public Criteria andHongLessThan(String value) {
            addCriterion("hong <", value, "hong");
            return (Criteria) this;
        }

        public Criteria andHongLessThanOrEqualTo(String value) {
            addCriterion("hong <=", value, "hong");
            return (Criteria) this;
        }

        public Criteria andHongLike(String value) {
            addCriterion("hong like", value, "hong");
            return (Criteria) this;
        }

        public Criteria andHongNotLike(String value) {
            addCriterion("hong not like", value, "hong");
            return (Criteria) this;
        }

        public Criteria andHongIn(List<String> values) {
            addCriterion("hong in", values, "hong");
            return (Criteria) this;
        }

        public Criteria andHongNotIn(List<String> values) {
            addCriterion("hong not in", values, "hong");
            return (Criteria) this;
        }

        public Criteria andHongBetween(String value1, String value2) {
            addCriterion("hong between", value1, value2, "hong");
            return (Criteria) this;
        }

        public Criteria andHongNotBetween(String value1, String value2) {
            addCriterion("hong not between", value1, value2, "hong");
            return (Criteria) this;
        }

        public Criteria andSevenDoubleIsNull() {
            addCriterion("seven_double is null");
            return (Criteria) this;
        }

        public Criteria andSevenDoubleIsNotNull() {
            addCriterion("seven_double is not null");
            return (Criteria) this;
        }

        public Criteria andSevenDoubleEqualTo(String value) {
            addCriterion("seven_double =", value, "sevenDouble");
            return (Criteria) this;
        }

        public Criteria andSevenDoubleNotEqualTo(String value) {
            addCriterion("seven_double <>", value, "sevenDouble");
            return (Criteria) this;
        }

        public Criteria andSevenDoubleGreaterThan(String value) {
            addCriterion("seven_double >", value, "sevenDouble");
            return (Criteria) this;
        }

        public Criteria andSevenDoubleGreaterThanOrEqualTo(String value) {
            addCriterion("seven_double >=", value, "sevenDouble");
            return (Criteria) this;
        }

        public Criteria andSevenDoubleLessThan(String value) {
            addCriterion("seven_double <", value, "sevenDouble");
            return (Criteria) this;
        }

        public Criteria andSevenDoubleLessThanOrEqualTo(String value) {
            addCriterion("seven_double <=", value, "sevenDouble");
            return (Criteria) this;
        }

        public Criteria andSevenDoubleLike(String value) {
            addCriterion("seven_double like", value, "sevenDouble");
            return (Criteria) this;
        }

        public Criteria andSevenDoubleNotLike(String value) {
            addCriterion("seven_double not like", value, "sevenDouble");
            return (Criteria) this;
        }

        public Criteria andSevenDoubleIn(List<String> values) {
            addCriterion("seven_double in", values, "sevenDouble");
            return (Criteria) this;
        }

        public Criteria andSevenDoubleNotIn(List<String> values) {
            addCriterion("seven_double not in", values, "sevenDouble");
            return (Criteria) this;
        }

        public Criteria andSevenDoubleBetween(String value1, String value2) {
            addCriterion("seven_double between", value1, value2, "sevenDouble");
            return (Criteria) this;
        }

        public Criteria andSevenDoubleNotBetween(String value1, String value2) {
            addCriterion("seven_double not between", value1, value2, "sevenDouble");
            return (Criteria) this;
        }

        public Criteria andRoomIdIsNull() {
            addCriterion("room_id is null");
            return (Criteria) this;
        }

        public Criteria andRoomIdIsNotNull() {
            addCriterion("room_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoomIdEqualTo(Integer value) {
            addCriterion("room_id =", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotEqualTo(Integer value) {
            addCriterion("room_id <>", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdGreaterThan(Integer value) {
            addCriterion("room_id >", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("room_id >=", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdLessThan(Integer value) {
            addCriterion("room_id <", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdLessThanOrEqualTo(Integer value) {
            addCriterion("room_id <=", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdIn(List<Integer> values) {
            addCriterion("room_id in", values, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotIn(List<Integer> values) {
            addCriterion("room_id not in", values, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdBetween(Integer value1, Integer value2) {
            addCriterion("room_id between", value1, value2, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotBetween(Integer value1, Integer value2) {
            addCriterion("room_id not between", value1, value2, "roomId");
            return (Criteria) this;
        }

        public Criteria andXiaYuIsNull() {
            addCriterion("xia_yu is null");
            return (Criteria) this;
        }

        public Criteria andXiaYuIsNotNull() {
            addCriterion("xia_yu is not null");
            return (Criteria) this;
        }

        public Criteria andXiaYuEqualTo(Integer value) {
            addCriterion("xia_yu =", value, "xiaYu");
            return (Criteria) this;
        }

        public Criteria andXiaYuNotEqualTo(Integer value) {
            addCriterion("xia_yu <>", value, "xiaYu");
            return (Criteria) this;
        }

        public Criteria andXiaYuGreaterThan(Integer value) {
            addCriterion("xia_yu >", value, "xiaYu");
            return (Criteria) this;
        }

        public Criteria andXiaYuGreaterThanOrEqualTo(Integer value) {
            addCriterion("xia_yu >=", value, "xiaYu");
            return (Criteria) this;
        }

        public Criteria andXiaYuLessThan(Integer value) {
            addCriterion("xia_yu <", value, "xiaYu");
            return (Criteria) this;
        }

        public Criteria andXiaYuLessThanOrEqualTo(Integer value) {
            addCriterion("xia_yu <=", value, "xiaYu");
            return (Criteria) this;
        }

        public Criteria andXiaYuIn(List<Integer> values) {
            addCriterion("xia_yu in", values, "xiaYu");
            return (Criteria) this;
        }

        public Criteria andXiaYuNotIn(List<Integer> values) {
            addCriterion("xia_yu not in", values, "xiaYu");
            return (Criteria) this;
        }

        public Criteria andXiaYuBetween(Integer value1, Integer value2) {
            addCriterion("xia_yu between", value1, value2, "xiaYu");
            return (Criteria) this;
        }

        public Criteria andXiaYuNotBetween(Integer value1, Integer value2) {
            addCriterion("xia_yu not between", value1, value2, "xiaYu");
            return (Criteria) this;
        }

        public Criteria andAddWordCardIsNull() {
            addCriterion("add_word_card is null");
            return (Criteria) this;
        }

        public Criteria andAddWordCardIsNotNull() {
            addCriterion("add_word_card is not null");
            return (Criteria) this;
        }

        public Criteria andAddWordCardEqualTo(String value) {
            addCriterion("add_word_card =", value, "addWordCard");
            return (Criteria) this;
        }

        public Criteria andAddWordCardNotEqualTo(String value) {
            addCriterion("add_word_card <>", value, "addWordCard");
            return (Criteria) this;
        }

        public Criteria andAddWordCardGreaterThan(String value) {
            addCriterion("add_word_card >", value, "addWordCard");
            return (Criteria) this;
        }

        public Criteria andAddWordCardGreaterThanOrEqualTo(String value) {
            addCriterion("add_word_card >=", value, "addWordCard");
            return (Criteria) this;
        }

        public Criteria andAddWordCardLessThan(String value) {
            addCriterion("add_word_card <", value, "addWordCard");
            return (Criteria) this;
        }

        public Criteria andAddWordCardLessThanOrEqualTo(String value) {
            addCriterion("add_word_card <=", value, "addWordCard");
            return (Criteria) this;
        }

        public Criteria andAddWordCardLike(String value) {
            addCriterion("add_word_card like", value, "addWordCard");
            return (Criteria) this;
        }

        public Criteria andAddWordCardNotLike(String value) {
            addCriterion("add_word_card not like", value, "addWordCard");
            return (Criteria) this;
        }

        public Criteria andAddWordCardIn(List<String> values) {
            addCriterion("add_word_card in", values, "addWordCard");
            return (Criteria) this;
        }

        public Criteria andAddWordCardNotIn(List<String> values) {
            addCriterion("add_word_card not in", values, "addWordCard");
            return (Criteria) this;
        }

        public Criteria andAddWordCardBetween(String value1, String value2) {
            addCriterion("add_word_card between", value1, value2, "addWordCard");
            return (Criteria) this;
        }

        public Criteria andAddWordCardNotBetween(String value1, String value2) {
            addCriterion("add_word_card not between", value1, value2, "addWordCard");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCardNumberIsNull() {
            addCriterion("card_number is null");
            return (Criteria) this;
        }

        public Criteria andCardNumberIsNotNull() {
            addCriterion("card_number is not null");
            return (Criteria) this;
        }

        public Criteria andCardNumberEqualTo(Integer value) {
            addCriterion("card_number =", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberNotEqualTo(Integer value) {
            addCriterion("card_number <>", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberGreaterThan(Integer value) {
            addCriterion("card_number >", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("card_number >=", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberLessThan(Integer value) {
            addCriterion("card_number <", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberLessThanOrEqualTo(Integer value) {
            addCriterion("card_number <=", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberIn(List<Integer> values) {
            addCriterion("card_number in", values, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberNotIn(List<Integer> values) {
            addCriterion("card_number not in", values, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberBetween(Integer value1, Integer value2) {
            addCriterion("card_number between", value1, value2, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("card_number not between", value1, value2, "cardNumber");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}