package com.chess.mybatis.mapper;

import com.chess.mybatis.entity.NoticeTable;
import com.chess.mybatis.entity.NoticeTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NoticeTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_table
     *
     * @mbggenerated
     */
    int countByExample(NoticeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_table
     *
     * @mbggenerated
     */
    int deleteByExample(NoticeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_table
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_table
     *
     * @mbggenerated
     */
    int insert(NoticeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_table
     *
     * @mbggenerated
     */
    int insertSelective(NoticeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_table
     *
     * @mbggenerated
     */
    List<NoticeTable> selectByExample(NoticeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_table
     *
     * @mbggenerated
     */
    NoticeTable selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_table
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") NoticeTable record, @Param("example") NoticeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_table
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") NoticeTable record, @Param("example") NoticeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NoticeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NoticeTable record);

    NoticeTable selectRecentlyObject();
}